In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('telecom_churn.csv')

df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,No,No,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [18]:
print(df.columns)
print(df.axes)
print(len(df))
print(df.attrs)

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')
[RangeIndex(start=0, stop=3333, step=1), Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')]
3333
{}

<h1> 3

In [3]:
print( np.sum(df.loc[:, ['Total day calls']], axis = 0) / len(df))

Total day calls    100.435644
dtype: float64

<h1> 4

In [4]:
df1 = df[df['State'] == 'OH']
print( np.sum(df1.loc[:, ['Total day calls']], axis = 0) / len(df1))

Total day calls    99.628205
dtype: float64

<h1> 5

In [20]:
states = df.State.unique()
#print(states)
TDCA = []

for state in states:
    df2 = df[df['State'] == state]
    TDCA.append(np.mean(df2['Total day calls']))
#print(ATDC)

df2 = pd.DataFrame(TDCA, index = states)
print(df2)

             0
KS  101.028571
OH   99.628205
NJ  100.102941
OK  100.262295
AL   99.100000
MA  102.292308
MO   99.936508
LA  103.509804
WV  103.783019
IN  107.056338
RI  100.430769
IA  103.045455
MT   95.220588
NY   98.240964
ID  106.219178
VT  100.328767
VA  105.363636
TX   99.986111
FL  101.000000
CO   95.121212
AZ  100.109375
SC  102.466667
NE   97.409836
WY  102.220779
HI  102.811321
IL  101.689655
NH   98.964286
GA  103.055556
AK   95.269231
MD   99.357143
AR  102.145455
WI   96.679487
OR   95.730769
MI  101.205479
DE   98.639344
UT   98.958333
CA  104.500000
MN   99.119048
SD   94.816667
NC  102.794118
WA  101.196970
NM  102.241935
NV  101.424242
DC  100.166667
KY  100.338983
ME   99.500000
MS  100.707692
TN  101.452830
PA   98.644444
CT   98.432432
ND  100.145161

<h1> 6

In [6]:
A = np.sum(df['Total day calls']) / len(df)
print(A)

df2 = df2[df2[0] > A]
print(df2)

100.43564356435644
             0
KS  101.028571
MA  102.292308
LA  103.509804
WV  103.783019
IN  107.056338
IA  103.045455
ID  106.219178
VA  105.363636
FL  101.000000
SC  102.466667
WY  102.220779
HI  102.811321
IL  101.689655
GA  103.055556
AR  102.145455
MI  101.205479
CA  104.500000
NC  102.794118
WA  101.196970
NM  102.241935
NV  101.424242
MS  100.707692
TN  101.452830

<h1> 7+8

In [12]:
dict = {}
dict['States'] = states
dict['Total day calls average'] = TDCA

TECA = []
DorE = []
for i in range(len(states)):
    df2 = df[df['State'] == states[i]]
    TECA.append(np.mean(df2['Total eve calls']))
    if TDCA[i] > TECA[i]:
        DorE.append(True)
    else:
        DorE.append(False)

dict['Total eve calls average'] = TECA
dict['Day > Evening'] = DorE
df3 = pd.DataFrame(dict)
print(df3)

   States  Total day calls average  Total eve calls average  Day > Evening
0      KS               101.028571               101.528571          False
1      OH                99.628205               101.205128          False
2      NJ               100.102941               103.441176          False
3      OK               100.262295               104.278689          False
4      AL                99.100000                98.462500           True
5      MA               102.292308                98.230769           True
6      MO                99.936508               101.047619          False
7      LA               103.509804                96.627451           True
8      WV               103.783019                98.056604           True
9      IN               107.056338                97.943662           True
10     RI               100.430769                94.969231           True
11     IA               103.045455                99.545455           True
12     MT                95.220588                97.514706          False
13     NY                98.240964               100.024096          False
14     ID               106.219178               100.054795           True
15     VT               100.328767                97.671233           True
16     VA               105.363636                99.948052           True
17     TX                99.986111               101.902778          False
18     FL               101.000000               108.920635          False
19     CO                95.121212                98.166667          False
20     AZ               100.109375               102.406250          False
21     SC               102.466667                99.783333           True
22     NE                97.409836               103.590164          False
23     WY               102.220779                99.233766           True
24     HI               102.811321                98.849057           True
25     IL               101.689655               100.810345           True
26     NH                98.964286                95.803571           True
27     GA               103.055556               103.888889          False
28     AK                95.269231                96.576923          False
29     MD                99.357143                98.571429           True
30     AR               102.145455                97.836364           True
31     WI                96.679487                99.538462          False
32     OR                95.730769                98.500000          False
33     MI               101.205479               101.986301          False
34     DE                98.639344                97.360656           True
35     UT                98.958333                98.027778           True
36     CA               104.500000               103.088235           True
37     MN                99.119048               101.642857          False
38     SD                94.816667                98.633333          False
39     NC               102.794118               103.941176          False
40     WA               101.196970                95.742424           True
41     NM               102.241935               102.983871          False
42     NV               101.424242                96.257576           True
43     DC               100.166667               101.981481          False
44     KY               100.338983                98.237288           True
45     ME                99.500000               104.596774          False
46     MS               100.707692               100.200000           True
47     TN               101.452830               103.754717          False
48     PA                98.644444               101.622222          False
49     CT                98.432432                99.121622          False
50     ND               100.145161               105.467742          False

<h1> 9

In [13]:
total = len(df)

intplan = len(df[df['International plan'] == 'Yes'])
vmailplan = len(df[df['Voice mail plan'] == 'Yes'])

print(intplan/total, vmailplan/total)

0.0969096909690969 0.27662766276627665

<h1> 10

In [29]:
print(len(df['Area code'].unique()))

3

<h1> 11

In [12]:
ring = df['Customer service calls' ].unique()
#print(ring)
cust = [len(df[df['Customer service calls'] == r]) for r in ring]

df3 = pd.DataFrame()
df3['Number of calls'] = np.array(ring)
df3['Number of customers'] = np.array(cust)
df3

   Number of calls  Number of customers
0                1                 1181
1                0                  697
2                2                  759
3                3                  429
4                4                  166
5                5                   66
6                7                    9
7                9                    2
8                6                   22
9                8                    2

<h1> 12

In [13]:
df[['Customer service calls', 'Churn']]

      Customer service calls  Churn
0                          1  False
1                          1  False
2                          0  False
3                          2  False
4                          3  False
...                      ...    ...
3328                       2  False
3329                       3  False
3330                       2  False
3331                       2  False
3332                       0  False

[3333 rows x 2 columns]

<h1> 13

In [15]:
np.mean(df['Total intl minutes'])

10.237293729372938

<h1> 14

In [21]:
day = np.array([np.sum(df['Total day minutes']), np.sum(df['Total day calls']), np.mean(df['Total day minutes'])])
eve = np.array([np.sum(df['Total eve minutes']), np.sum(df['Total eve calls']), np.mean(df['Total eve minutes'])])
nig = np.array([np.sum(df['Total night minutes']), np.sum(df['Total night calls']), np.mean(df['Total night minutes'])])

df4 = pd.DataFrame()
df4['day'] = day
df4['evening'] = eve
df4['night'] = nig
df4

             day        evening          night
0  599190.400000  669867.500000  669506.500000
1  334752.000000  333681.000000  333659.000000
2     179.775098     200.980348     200.872037

<h1> 15

In [18]:
st = df[df['Churn'] == False]
le = df[df['Churn'] == True]

print('stayed')
print(np.sum(st['Total day charge']))
print('left')
print(np.sum(le['Total day charge']))

stayed
84874.2
left
16989.97

<h1> 16

In [27]:
dict = {}

for state in df['State'].unique():
    dict[state] = np.sum(df[df['State'] == state]['Total day calls'])

sorted(dict, key = lambda x: x[1])

['MA',
 'LA',
 'IA',
 'VA',
 'GA',
 'CA',
 'WA',
 'PA',
 'SC',
 'NC',
 'DC',
 'ID',
 'MD',
 'SD',
 'ND',
 'NE',
 'DE',
 'ME',
 'OH',
 'NH',
 'RI',
 'HI',
 'WI',
 'MI',
 'NJ',
 'OK',
 'AK',
 'AL',
 'FL',
 'IL',
 'NM',
 'IN',
 'MN',
 'TN',
 'MO',
 'CO',
 'AR',
 'OR',
 'KS',
 'MS',
 'MT',
 'VT',
 'UT',
 'CT',
 'WV',
 'NV',
 'TX',
 'NY',
 'WY',
 'KY',
 'AZ']