In [24]:
import pandas as pd
import numpy as np

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

<h1> 2

In [35]:
df = pd.DataFrame([[1, np.nan, np.nan, np.nan],
                   [np.nan, 1, np.nan, np.nan],
                   [np.nan, np.nan, 1, np.nan],
                   [np.nan, np.nan, np.nan, 1]],
                columns=list("ABCD"))

df[['A', 'B']] = df[['A', 'B']].fillna(2)
df.loc[0] = df.loc[0].fillna(1)
df['C'] = df['C'].fillna(2)
df = df.fillna(value = 1)
print(df)

     A    B    C    D
0  1.0  2.0  1.0  1.0
1  2.0  1.0  2.0  1.0
2  2.0  2.0  1.0  1.0
3  2.0  2.0  2.0  1.0

<h1> 3

In [23]:
m = 10
c = ''
for column in df.columns:
    if np.sum(df[column]) < m:
        c = column

df = df.drop([c], axis = 1)
print(df)

     A    B    C
0  1.0  2.0  1.0
1  2.0  1.0  2.0
2  2.0  2.0  1.0
3  2.0  2.0  2.0

<h1> -------------------------------------------------------------------------------------------------------------

In [42]:
df = pd.read_csv('train.csv')

In [44]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

<h1> 4

In [45]:
print(np.mean(df['Age']))

29.69911764705882

<h1> 5

In [105]:
#print(df['Age'])
print(df.loc[df['Age'] == np.min(df['Age'])]['Name'])

803    Thomas, Master. Assad Alexander
Name: Name, dtype: object

<h1> 6

In [63]:
pcls = df['Pclass'].unique()

for pcl in pcls:
    print(str(pcl) + ' ' + str(len(df.loc[df['Pclass'] == pcl]) / len(df)))

3 0.5510662177328844
1 0.24242424242424243
2 0.20650953984287318

<h1> 7

In [64]:
for pcl in pcls:
    print(str(pcl) + ' ' + str(np.mean(df.loc[df['Pclass'] == pcl]['Age'])))

3 25.14061971830986
1 38.233440860215055
2 29.87763005780347

<h1> 8

In [101]:
'''
sk = []
for column in df.columns:
    sk.append(df.isna().sum())
print(sk)
'''

sk = (df.isna().sum()).sort_values()
#print(sk)
#print(type(sk.loc[sk == sk.iloc[-1]].index[0]))
df1 = df.drop(sk.loc[sk == sk.iloc[-1]].index, axis = 1)
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

<h1> 9

In [115]:
unm = 0
unc = ''

for column in df.columns:
    if df[column].unique().size > unm:
        unm = df[column].unique().size
        unc = column

#print(unc, unm)
df1 = df.drop([unc], axis = 1)
df1

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

<h1> 10

In [133]:
dfs = df.loc[df['Survived'] == 1]
dfm = dfs.loc[dfs['Sex'] == 'male']
dff = dfs.loc[dfs['Sex'] == 'female']
'''
dfsm = dfs.merge(dfm, how = 'inner', on = ['Name'])
dfsf = dfs.merge(dff, how = 'inner', on = ['Name'])
'''
print(len())
print(len(dfsm)/len(dfm))
print(len(dfsf)/len(dff))
dfm

0.3847019122609674
1.0
1.0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

<h1> 11

In [126]:
for pcl in pcls:
    print(str(pcl) + ' ' + str(len(dfs.loc[dfs['Pclass'] == pcl])/len(dfs)))

3 0.347953216374269
1 0.39766081871345027
2 0.2543859649122807

<h1> 12

In [ ]:
dfs1 = dfs.loc(dfs['Age'] < 18)
print(len(dfs1)/len)